### ISSUE TITLE
Release version in CMake

### ISSUE THREAD

**Issue by sagitter** [PASSIONLab/CombBLAS#16]
Hi all.

Why current CombBLAS version is still 1.16.0?
https://github.com/PASSIONLab/CombBLAS/blob/v2.0.0/CMakeLists.txt#L2

**Comment by drew-parsons** [comment]
Is the new 2.0.0 release binary (ABI) compatible with the old 1.16 library?  That doesn't seem likely.  Should a new v2.0.1 tag be made fixing the version number in CMakeLists.txt ?

**Comment by aydinbuluc** [comment]
It is just a leftover line in the CMakeList. It should have said 2.0.0 
Happy to accept a pull request if that creates issues.

**Comment by drew-parsons** [comment]
I've created PR #18 to fix this.

**Comment by drew-parsons** [comment]
There is a related question: are CombBLAS shared libraries expected to be ABI stable?  i.e. is v2.0.1 (or v2.1.0) expected to be binary compatible with v2.0.0 ?

If that's the case then it could be helpful to configure CMakeFiles.txt to set the SOVERSION for shared libaries.  This can be done separately from the project version.

By default the soname is set using the project version, but this might be overkill, since it means v2.0.1 would be treated as binary incompatible with v2.0.0.
